In [435]:
import cv2
from ipywidgets import Video
import ipywidgets as widgets
from IPython.display import display
import numpy as np

In [436]:
video_capture = cv2.VideoCapture('Chess_Data\\chess_easy1.mp4')

### Full detection

In [437]:
def find_closest_points_to_corners(points, corners):
    closest_points = []
    for corner in corners:
        distances = np.linalg.norm(points - corner, axis=1)
        closest_point_index = np.argmin(distances)
        closest_points.append(points[closest_point_index])
    return np.array(closest_points)

def calculate_change(x1, x2, num_divisons=8):
    return (x2-x1)/num_divisons

while True:
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(gray, 50, 150)

    frame_with_boxes = frame.copy()
    dst = cv2.cornerHarris(blurred, 5, 3, 0.02)
    dst = cv2.dilate(dst, None)
    corners = np.argwhere(dst > 0.01 * dst.max())

    image_corners = np.array([[0, 0], [0, frame.shape[1]], [frame.shape[0], 0], [frame.shape[0], frame.shape[1]]])
    closest_corners = find_closest_points_to_corners(corners, image_corners)
    print(closest_corners)

    #Finding vertical lines
    top_x = calculate_change(closest_corners[1][1], closest_corners[0][1])
    top_y = calculate_change(closest_corners[1][0], closest_corners[0][0])
    bottom_x = calculate_change(closest_corners[3][1], closest_corners[2][1])
    bottom_y = calculate_change(closest_corners[3][0], closest_corners[2][0])
    topxy = closest_corners[1]
    bottomxy = closest_corners[3]

    for i in range(1,8):
        new_point_top = topxy+i*np.array([top_y,top_x])
        new_point_top = new_point_top.astype(int)
        new_point_bottom = bottomxy+i*np.array([bottom_y,bottom_x])
        new_point_bottom = new_point_bottom.astype(int)

        cv2.circle(frame_with_boxes, tuple(new_point_top[::-1]), radius=5, color=(255, 0, 0), thickness=-1)
        cv2.circle(frame_with_boxes, tuple(new_point_bottom[::-1]), radius=5, color=(255, 0, 0), thickness=-1)
        cv2.line(frame_with_boxes, tuple(new_point_top[::-1]), tuple(new_point_bottom[::-1]), color=(0, 0, 255), thickness=2)

    #Finding horizontal lines
    left_x = calculate_change(closest_corners[2][1], closest_corners[0][1])
    left_y = calculate_change(closest_corners[2][0], closest_corners[0][0])
    right_x = calculate_change(closest_corners[3][1], closest_corners[1][1])
    right_y = calculate_change(closest_corners[3][0], closest_corners[1][0])
    leftxy = closest_corners[2]
    rightxy = closest_corners[3]

    for i in range(1,8):
        new_point_left = leftxy+i*np.array([left_y,left_x])
        new_point_left = new_point_left.astype(int)
        new_point_right = rightxy+i*np.array([right_y,right_x])
        new_point_right = new_point_right.astype(int)

        cv2.circle(frame_with_boxes, tuple(new_point_left[::-1]), radius=5, color=(255, 0, 0), thickness=-1)
        cv2.circle(frame_with_boxes, tuple(new_point_right[::-1]), radius=5, color=(255, 0, 0), thickness=-1)
        cv2.line(frame_with_boxes, tuple(new_point_left[::-1]), tuple(new_point_right[::-1]), color=(0, 0, 255), thickness=2)  

    trapezoid_pts = np.array([[closest_corners[0][1], closest_corners[0][0]], 
                              [closest_corners[2][1], closest_corners[2][0]], 
                              [closest_corners[3][1], closest_corners[3][0]], 
                              [closest_corners[1][1], closest_corners[1][0]]], np.int32)
    trapezoid_pts = trapezoid_pts.reshape((-1, 1, 2))

    cv2.polylines(frame_with_boxes, [trapezoid_pts], isClosed=True, color=(0, 255, 0), thickness=2)

    for corner in closest_corners:
        cv2.circle(frame_with_boxes, tuple(corner[::-1]), 5, (0, 0, 255), -1)

    cv2.imshow('Frame with Trapezoid', frame_with_boxes)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

[[  47  406]
 [  50 1420]
 [1034  275]
 [1040 1507]]
[[  47  406]
 [  50 1419]
 [1033  275]
 [1039 1507]]
[[  48  405]
 [  50 1419]
 [1034  275]
 [1039 1507]]
[[  48  405]
 [  50 1419]
 [1033  274]
 [1039 1507]]
[[  48  405]
 [  50 1420]
 [1032  274]
 [1039 1507]]
[[  48  404]
 [  49 1419]
 [1033  275]
 [1039 1507]]
[[  46  406]
 [  49 1419]
 [1032  274]
 [1040 1507]]
[[  47  405]
 [  49 1419]
 [1034  275]
 [1040 1507]]
[[  47  405]
 [  50 1419]
 [1034  275]
 [1041 1507]]
[[  47  406]
 [  50 1419]
 [1034  274]
 [1040 1507]]
[[  47  406]
 [  51 1420]
 [1034  274]
 [1042 1507]]
[[  48  405]
 [  51 1419]
 [1035  275]
 [1042 1507]]
[[  49  406]
 [  51 1419]
 [1035  274]
 [1042 1508]]
[[  50  406]
 [  53 1419]
 [1037  275]
 [1043 1507]]
[[  52  406]
 [  55 1420]
 [1038  275]
 [1044 1508]]
[[  52  406]
 [  54 1420]
 [1039  275]
 [1044 1508]]
[[  52  407]
 [  55 1420]
 [1039  275]
 [1046 1508]]
[[  55  406]
 [  57 1420]
 [1040  275]
 [1047 1508]]
[[  55  406]
 [  57 1420]
 [1041  275]
 [1047 

In [438]:
import cv2
import numpy as np

def find_closest_points_to_corners(points, corners):
    closest_points = []
    for corner in corners:
        distances = np.linalg.norm(points - corner, axis=1)
        closest_point_index = np.argmin(distances)
        closest_points.append(points[closest_point_index])
    return np.array(closest_points)

while True:
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(gray, 50, 150)

    frame_with_boxes = frame.copy()
    dst = cv2.cornerHarris(blurred, 5, 3, 0.02)
    dst = cv2.dilate(dst, None)
    corners = np.argwhere(dst > 0.01 * dst.max())

    # Find corners closest to image corners
    image_corners = np.array([[0, 0], [0, frame.shape[1]], [frame.shape[0], 0], [frame.shape[0], frame.shape[1]]])
    closest_corners = find_closest_points_to_corners(corners, image_corners)

    # Draw the resulting trapezoid
    #cv2.polylines(frame_with_boxes, [closest_corners], isClosed=True, color=(0, 255, 0), thickness=2)
    #frame_with_boxes[dst > 0.01 * dst.max()] = [0, 0, 255]

    trapezoid_pts = np.array([[closest_corners[0][1], closest_corners[0][0]], [closest_corners[2][1], closest_corners[2][0]], [closest_corners[3][1], closest_corners[3][0]], [closest_corners[1][1], closest_corners[1][0]]], np.int32)
    trapezoid_pts = trapezoid_pts.reshape((-1, 1, 2))
    cv2.polylines(frame_with_boxes, [trapezoid_pts], isClosed=True, color=(0, 255, 0), thickness=2)


    for corner in closest_corners:
        cv2.circle(frame_with_boxes, tuple(corner[::-1]), 5, (0, 0, 255), -1)

    # Display the result
    cv2.imshow('Frame with Trapezoid', frame_with_boxes)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

In [439]:
while True:   
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    frame_with_boxes = frame.copy()
    total_area = frame.shape[0] * frame.shape[1]
    giant_contour = np.vstack(contours)

    # Calculate the bounding box of the giant contour
    x, y, w, h = cv2.boundingRect(giant_contour)
    dst = cv2.cornerHarris(gray, 3, 3, 0.04)
    dst = cv2.dilate(dst, None)
    corners = np.argwhere(dst > 0.01 * dst.max())

    lc = np.min(corners[:, 0])
    tc = np.min(corners[:, 1])
    rc = np.max(corners[:, 0])
    bc = np.max(corners[:, 1])
    frame_with_boxes[dst > 0.01 * dst.max()] = [0, 0, 255]

    # Draw the resulting bounding box
    cv2.rectangle(frame_with_boxes, (tc, lc), (bc, rc), (0, 255, 0), 2)

    # Display the result
    cv2.imshow('Frame with Giant Bounding Box', frame_with_boxes)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

In [440]:
while True:   
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    frame_with_boxes = frame.copy()
    total_area = frame.shape[0] * frame.shape[1]
    giant_contour = np.vstack(contours)

    # Calculate the bounding box of the giant contour
    x, y, w, h = cv2.boundingRect(giant_contour)
    dst = cv2.cornerHarris(gray, 3, 3, 0.04)
    dst = cv2.dilate(dst, None)
    corners = np.argwhere(dst > 0.01 * dst.max())

    lc = np.min(corners[:, 0])
    tc = np.min(corners[:, 1])
    rc = np.max(corners[:, 0])
    bc = np.max(corners[:, 1])
    frame_with_boxes[dst > 0.01 * dst.max()] = [0, 0, 255]

    # Draw the resulting bounding box
    cv2.rectangle(frame_with_boxes, (tc, lc), (bc, rc), (0, 255, 0), 2)

    # Display the result
    cv2.imshow('Frame with Giant Bounding Box', frame_with_boxes)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

In [441]:
while True:
    ret, frame = video_capture.read()
    if not ret:
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    frame_with_boxes = frame.copy()
    total_area = frame.shape[0] * frame.shape[1]
    threshold_lower = 0
    threshold_upper = np.inf
    for contour in contours:
        area = cv2.contourArea(contour)
        if area > threshold_lower and area<threshold_upper:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame_with_boxes, (x, y), (x + w, y + h), (0, 255, 0), 2)
    # Display the result
    dst = cv2.cornerHarris(gray, 3, 3, 0.04)
    # result is dilated for marking the corners, not important
    dst = cv2.dilate(dst, None)

    # Threshold for an optimal value, it may vary depending on the image.
    frame[dst > 0.01 * dst.max()] = [0, 0, 255]
    cv2.imshow('Frame with Boxes', frame_with_boxes)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture and close windows
video_capture.release()
cv2.destroyAllWindows()

In [442]:
while True:
    ret, frame = video_capture.read()
    if not ret:
        break

    # Convert the frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Apply Gaussian blur
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Use Canny edge detection
    edges = cv2.Canny(blurred, 50, 150)

    # Use HoughLinesP to detect lines in the edges
    lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50, minLineLength=50, maxLineGap=10)

    # Draw the detected lines on the original frame
    frame_with_lines = frame.copy()
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            cv2.line(frame_with_lines, (x1, y1), (x2, y2), (0, 255, 0), 2)

    # Display the frame with detected lines
    cv2.imshow('Frame with Lines', frame_with_lines)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture and close windows
video_capture.release()
cv2.destroyAllWindows()

### Keypoint Detection

In [443]:
sift = cv2.SIFT_create()

while True:   
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    sift_kp1, sift_desc1 = sift.detectAndCompute(gray, None)
    img_kp1 = cv2.drawKeypoints(
        frame, sift_kp1, None, flags=cv2.DRAW_MATCHES_FLAGS_DEFAULT
    )

    cv2.imshow('Video Frame', img_kp1)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

### Corner Detection

In [444]:
while True:   
    ret, frame = video_capture.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)
    dst = cv2.cornerHarris(gray, 3, 3, 0.04)
    # result is dilated for marking the corners, not important
    dst = cv2.dilate(dst, None)

    # Threshold for an optimal value, it may vary depending on the image.
    frame[dst > 0.01 * dst.max()] = [0, 0, 255]

    cv2.imshow('Video Frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()